### ISSUE TITLE
Can not use on Linux Arm

### ISSUE THREAD

**Issue by smcclure15** [coverallsapp/coverage-reporter#137]
### What was wrong?
```
$ curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C .
$ ./coveralls --help
bash: ./coveralls: cannot execute binary file: Exec format error
```
I think this is only for x86 arch, whereas I am on an Arm arch:
```
$ arch
aarch64
```

**Comment by afinetooth** [comment]
@smcclure15 checking it out...

**Comment by afinetooth** [comment]
@smcclure15 what flavor of Linux are you using?

**Comment by smcclure15** [comment]
ubuntu 22.04

**Comment by afinetooth** [comment]
@smcclure15 OK, a couple of options / next steps here:

1. I'm seeing how quickly we can cut a new release of `coverage-reporter` (`coveralls-linux`) cross-compiled for `x86_64` and `aarch64`. We should probably be doing so in the first place.
2. I'm drafting instructions for building `coverage-reporter` on `aarch64` that you could use in the meantime, if you like. We have a number of customers who build `coverage-reporter` themselves, for reasons of security, efficiency, or what in this case would be compatibility.

**Question**:

- Are you interested in (2)? Or would you rather wait for (1)?  Or both?

**Comment by smcclure15** [comment]
(1) is what I'm after.
For context, I'm currently using [gcovr](https://github.com/gcovr/gcovr) to go from `.gcda` directly to coveralls json format, but I know we'll soon have other tools that will produce `lcov` format, so I'll have to transform that to coveralls json anyway, so I was seeing what this tool could do for me.

**Comment by afinetooth** [comment]
@smcclure15 OK, great, thanks.

We are hopeful (1) will be available tomorrow. I'll update you via normal channels. 

_**Note**: I will post (2) here in a separate comment for anyone else tuning in who wants to build `coverage-reporter` themselves._

> For context, I'm currently using [gcovr](https://github.com/gcovr/gcovr) to go from .gcda directly to coveralls json format, but I know we'll soon have other tools that will produce lcov format, so I'll have to transform that to coveralls json anyway, so I was seeing what this tool could do for me.

Got it. Thanks for the context.

All [Coveralls integrations](https://docs.coveralls.io/integrations) do the same basic thing, minimally, which is convert a coverage report found in the local CI environment from its native format into Coveralls JSON.

We recommend our [official integrations](https://docs.coveralls.io/integrations#official-integrations) because we can support your entire toolchain, and they will convert from many different native formats into Coveralls JSON for you. `LCOV` being perhaps the most ubiquitously available native format, it's at the top of our list of [supported coverage report formats](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#supported-coverage-report-formats). 

I would definitely let _some_ integration---_any_ integration---perform that conversion for you, and [coverage-reporter](https://github.com/coverallsapp/coverage-reporter) is your best choice of [official integration](https://docs.coveralls.io/integrations) if you aren't using GitHub Actions or CircleCI for CI. Although, even if you _are_ using either of those, [coverage-reporter](https://github.com/coverallsapp/coverage-reporter) will give you more control over the process.

**Comment by afinetooth** [comment]
Duplicated in this issue: [github-action #218](https://github.com/coverallsapp/github-action/issues/218)

**Comment by smcclure15** [comment]
Is this resolved or not?

I can repro the original:
```
$ curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C .
$ ./coveralls --help
bash: ./coveralls: cannot execute binary file: Exec format error
```

And peeking into what merged, I tried the `-aarch64` url, to no avail:
```
$ curl -L https://coveralls.io/coveralls-linux-aarch64.tar.gz | tar -xz -C .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2946    0  2946    0     0  25130      0 --:--:-- --:--:-- --:--:-- 24966

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by afinetooth** [comment]
Hi @smcclure15. Not yet. We are still testing and hope to complete this week. We've run into multiple issues cross-compiling linux binaries for `aarch64` when testing on different Linux varieties. 

Which reminds me to ask: You are using Ubuntu 22.04, right? Do you think you will need `aarch64` binaries for Alpine or Debian, or Centos, anytime soon? Or will Ubuntu serve your needs for at least the next 2-4 weeks?

Being Rubyists, our coverage-reporter was written in Crystal, which is the reason for the relative lack of support for cross-compilation, primarily in libraries for static linking across platforms. Our long-term plan is to migrate coverage-reporter to `go`, or similar, but for now, we think we've found our solution for cross-compiling to Ubuntu (`aarch64`).

**Comment by smcclure15** [comment]
Can this issue remain Open until it is resolved?

And yes, ubuntu should suffice for my needs.

**Comment by afinetooth** [comment]
Totally. I have re-opened it. (Closing it was a mistake---I don't remember doing it or know why I would have, but I do see it in the history so my bad!)

> And yes, ubuntu should suffice for my needs.

Great. Thanks.

**Comment by afinetooth** [comment]
Closing this. Please open a new issue if your are looking for help with the [Linux (`aarch64`)-compatible version of coverage-reporter](https://github.com/coverallsapp/coverage-reporter/issues/137#issuecomment-2394337536) (`v0.6.15`+).

**Comment by afinetooth** [comment]
For users of coverage-reporter through the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action):

Per [this related update at coverallsapp/github-action](https://github.com/coverallsapp/github-action/issues/218#issuecomment-2436338747), [release `v2.3.4` of the `github-action`](https://github.com/coverallsapp/github-action/releases/tag/v2.3.4) now supports the `coverage-reporter-platform` input option, with values of [`x86_64` | `aarch64` (or `arm64`)].

You can use the latest version of the `github-action` (in this case `v2.3.4`) simply by continuing to use `coverallsapp/github-action@v2` in your workflows.

**Comment by afinetooth** [comment]
@smcclure15 ^^ in case your other users need `arm64` support, but are using the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action).

**Comment by afinetooth** [comment]
For users of `coverage-reporter` through the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls):

As of its [`v2.2.5` release](https://github.com/coverallsapp/orb/releases/tag/v2.2.5), our `orb` supports the [`coverage_reporter_platform` input parameter](https://circleci.com/developer/orbs/orb/coveralls/coveralls#:~:text=string-,coverage_reporter_platform,reporter%20to%20use.%20Supported%20values%3A%20x86_64%20(default)%20and%20aarch64%20(or%20arm64).,-No), with values of [`x86_64` | `aarch64` (or `arm64`)].
