### ISSUE TITLE
Does coverage-reporter support cpp bazel coverage output format?

### ISSUE THREAD

**Issue by aaron-ai** [coverallsapp/coverage-reporter#47]
### Question

Does coverage-reporter support cpp bazel coverage output format?

We generate coverage file by `bazel coverage  //...`.

**Comment by mrexox** [comment]
Hey! As long as I understand from the [docs](https://bazel.build/configure/coverage#viewing_coverage) bazel creates coverage report in LCOV format. **coverage-reporter** supports LCOV, however, as they say, the coverage report filename is something like `_coverage_report.dat`, so for correct parsing I suggest providing `--filename <path-to _coverage_report.dat>` and `--format lcov` options. 

**coverage-reporter** won't be able to automatically detect the format of this file since it uses filename patterns to detect it, and for LCOV filenames should end with `.lcov` or `lcov.info`

If you face any issues with the bazel reports, please create an issue or extend this one, and I'll be glad to help :)
