### ISSUE TITLE
Support Linux arm64 architecture

### ISSUE THREAD

**Issue by gabotechs** [coverallsapp/coverage-reporter#68]
I am using GitHub actions with EC2 self hosted runners, but the downloaded binary `https://coveralls.io/coveralls-linux.tar.gz` only works for x86_64 architectures.

This leads to the following error while trying to use the `coverage-reporter` binary:
```shell
/home/ec2-user/bin/coveralls: cannot execute binary file: Exec format error
```

It would be awesome if this project also publishes an additional binary compiled for linux arm64 architectures.

**Comment by mrexox** [comment]
Hey! Totally agree. We have a task to add support for more architectures, unfortunately it's going to take a while, since cross-compilation is rather tricky for Crystal. 

If you want a quick workaround you can build coverage-reporter on your EC2 runner and put it somewhere accessible from the PATH. The only dependencies - Crystal and SQLite3 dev library. I can help you setup the CI based on Github action setup your use now. Does it work for you?

**Comment by gabotechs** [comment]
> I can help you setup the CI based on Github action setup your use now. Does it work for you?

Thank you! but that will not be necessary, I got it working by just using the `coverallsapp/github-action@v1` action, which does not rely on crystal. As I only care about `lcov` format that works fine for me.

**Comment by afinetooth** [comment]
For anyone else who's looking for this, MacOS Linux / Linux Arm 64 architecture / aarch64 is now supported via `homebrew`. See [installation instructions here](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#macos).
